### ISSUE TITLE
Add "coming soon" message

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick-docs-tr#1]
Hi @Zeynepelabiad! Now that we have created a placeholder for the Turkish-language Yellowbrick documentation, could you translate the following statement and add it to [index.rst](https://github.com/DistrictDataLabs/yellowbrick-docs-tr/blob/master/docs/index.rst)?

> Welcome to Yellowbrick! 
>
> We are currently working on a Turkish-language translation of the documentation, so please come back soon.
>
> Also, we're always looking for help! If you'd like to contribute to the translation, you can submit a pull request to [yellowbrick-docs-tr](https://github.com/DistrictDataLabs/yellowbrick-docs-tr). If you're interested in contributing to Yellowbrick, you can submit a pull request to the [codebase](https://github.com/DistrictDataLabs/yellowbrick).

**Comment by Zeynepelabiad** [comment]
Hi @rebeccabilbro .  I just added the Turkish statement to index.rst page. Can you please check? Also I will be translating index, about, user texting instructor pages of Turkish Yellowbrick until March 28, 2018.

**Comment by rebeccabilbro** [comment]
Fantastic, it's live [here](http://www.scikit-yb.org/tr/latest/) now - nice work @Zeynepelabiad!!
